steps:
  # Install dependencies
  - name: "node:18"
    entrypoint: npm
    args: ["install"]

  # Build the function
  - name: "node:18"
    entrypoint: npm
    args: ["run", "build"]

  # Deploy to Cloud Functions
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - functions
      - deploy
      - hello-world
      - --gen2
      - --runtime=nodejs18
      - --region=asia-northeast1
      - --source=.
      - --entry-point=helloGET
      - --trigger-http
      - --allow-unauthenticated
      - --env-vars-file=env.gcloud.yml
